### ISSUE TITLE
Restore check_version

### ISSUE THREAD

**Issue by chrisjbillington** [labscript-suite/labscript-utils#62]
labscript_utils 3.0.0 removed the check_version function. This was because it was no longer used by the labscript suite, which now manages its dependencies using pip/conda. However, code that is distributed in forms other than packages on PyPI/anaconda cloud, particularly code living in userlib, cannot use pip/conda to manage versions of its dependencies, so it is still useful to provide a function to do runtime checks.

So we should add it back in

See brief discussion [here](https://github.com/labscript-suite/labscript-utils/pull/42#issuecomment-650474657)

**Comment by philipstarkey** [comment]
I think we should add it back in. We should consider not `distutils.version` though (which I believe is both undocumented and not PEP440 compliant). Instead we should probably use `packaging.version` which is also already in our dependency tree (`setuptools_scm` depends on `setuptools` which depends on `packaging`). My understanding is that `packaging.version` handles comparison of development versions correctly (which is why I used it in #61)

**Comment by chrisjbillington** [comment]
Excellent, sounds like packaging.version is the way to go then.
