### ISSUE TITLE
Version not reported correctly from conda install

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite/labscript-utils#95]
Got a report on the mailing list that accessing the `__version__` attribute returns 0.0.0 when installed via conda.

**Comment by dihm** [comment]
Done some sleuthing and it appears that this issue has existed in the conda builds since v3.1.0rc1 (confirmable by checking the tarballs on the [conda channel](https://anaconda.org/labscript-suite/labscript-utils/files) and looking at the dist-info folder name in site-packages).

Further checking and it appears to have been an issue in the github workflow that has been fixed (probably #89), we just haven't released an official version with the updated workflow yet so the fix hasn't propagated to the conda channel.

I'll tag a minor version.

**Comment by dihm** [comment]
This is fixed with v3.2.2 ([29a40a0](https://github.com/labscript-suite/labscript-utils/commit/29a40a0d887ae96ca68958a101d92e01662a1dfa))
